### ISSUE TITLE
Switch to readthedocs ?

### ISSUE THREAD

**Issue by nikhilCad** [Orama-Interactive/Pixelorama-Docs#2]
I am just saying it beacuse Godot uses readthedocs too, and it might be easier for a contributor their to contribute in the docs here.
Though I think readthedocs pages are kind of less fancy.

**Comment by OverloadedOrama** [comment]
I'm not sure if that necessary, Docusaurus seems to be doing a good job so far and it's fairly easy to edit, all the contributors have to do is edit the `.md` files. Plus Docusaurus comes with Crowdin integration, which can be useful later on for translations, especially since Pixelorama itself already uses Crowdin.

**Comment by Schweini07** [comment]
For a project like Pixelorama I would say Docusaurus is the better option.

**Comment by nikhilCad** [comment]
Closing. Crowdin translation support cant be lost.
